server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/db/memberdb3;MODE=MYSQL
    username: sa
    password: 1234


  jpa:
    properties:
      hibernate:
        show_sql: ture
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
